name: flatter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.0-beta6
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0-nullsafety.4
  intl: ^0.17.0
  json_annotation: ^4.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^4.0.0
  pedantic: ^1.11.0

flutter:
  generate: true
  uses-material-design: true
