name: flatter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.0.0
  dio: ^5.5.0
  equatable: ^2.0.0
  flutter_bloc: ^8.0.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  json_serializable: ^6.1.0

flutter:
  generate: true
  uses-material-design: true
